"""Stage 9: verify the provenance chain and write PROVENANCE.md.

Reads every outputs/provenance/s0*.json record and checks:
  1. every file a stage read is either an upstream download (recorded with
     its URL by s02_fetch), the fingerprinted source database (s01), or the
     output of an earlier stage, and its hash at read time equals the hash
     recorded when it was written (no file was modified between stages);
  2. every stage ran with the same config.py (identical config hash);
  3. every output file still has the recorded hash on disk now;
  4. every file in outputs/ (other than the provenance records themselves)
     was produced by a stage.
Then writes PROVENANCE.md: the lineage of every output back to its sources,
with hashes, row counts, URLs, and the stage notes (the audit trail).
A failed check makes this stage exit non-zero.
"""
import glob
import json
import os
import sys

from config import OUT_DIR, PROV_DIR, ROOT
from provenance import Stage, rel, sha256_file

ORDER = ["s01_extract", "s02_fetch", "s03_locate", "s04_units", "s05_blocks",
         "s06_census", "s07_analyze", "s08_map"]


def main():
    problems = []
    recs = {}
    for name in ORDER:
        p = os.path.join(PROV_DIR, name + ".json")
        if not os.path.exists(p):
            problems.append(f"missing provenance record for {name}")
            continue
        with open(p) as f:
            recs[name] = json.load(f)
        if not recs[name].get("ok"):
            problems.append(f"{name} did not finish successfully")

    produced = {}      # rel path -> (stage, sha256, url)
    config_hashes = set()
    for name in ORDER:
        r = recs.get(name)
        if not r:
            continue
        config_hashes.add(r["config_sha256"])
        for o in r["outputs"]:
            produced[o["path"]] = (name, o["sha256"], o.get("url"))
    if len(config_hashes) > 1:
        problems.append(f"stages ran with different config.py versions: {sorted(config_hashes)}")

    # Check 1: inputs trace to a producer and hashes match.
    for name in ORDER:
        r = recs.get(name)
        if not r:
            continue
        for i in r["inputs"]:
            path = i["path"]
            if "sha256_partial" in i:
                if name != "s01_extract":
                    problems.append(f"{name}: partial hash used for non-source input {path}")
                continue
            if path not in produced:
                problems.append(f"{name}: input {path} was not produced by any earlier stage")
                continue
            pstage, phash, _ = produced[path]
            if ORDER.index(pstage) >= ORDER.index(name):
                problems.append(f"{name}: input {path} produced by a later stage ({pstage})")
            if phash != i["sha256"]:
                problems.append(f"{name}: input {path} hash {i['sha256'][:12]} != {pstage} output {phash[:12]}")
    # Check 3: outputs unchanged on disk.
    for path, (stage, h, _) in produced.items():
        full = os.path.join(ROOT, path)
        if not os.path.exists(full):
            problems.append(f"output {path} from {stage} is missing on disk")
        elif sha256_file(full) != h:
            problems.append(f"output {path} from {stage} has changed on disk since it was written")
    # Check 4: everything in outputs/ is accounted for.
    for full in sorted(glob.glob(os.path.join(OUT_DIR, "**", "*"), recursive=True)):
        if os.path.isdir(full) or full.startswith(PROV_DIR) or full.endswith(("audit.log", "PROVENANCE.md")):
            continue
        if rel(full) not in produced:
            problems.append(f"unaccounted file in outputs/: {rel(full)}")

    # ---- write PROVENANCE.md ------------------------------------------------
    lines = ["# Provenance", "",
             "Generated by s09_provenance.py from the per-stage records in outputs/provenance/.",
             "Every output traces to an upstream download (URL + sha256), or to the source",
             "database fingerprint, through the chain of stage inputs and outputs below.",
             "Hashes are sha256; sizes are bytes.", ""]
    lines += ["## Verification", ""]
    if problems:
        lines += ["**FAILED**", ""] + [f"- {p}" for p in problems] + [""]
    else:
        lines += ["All checks passed: every stage input matches the hash of the stage output or",
                  "upstream download that produced it; all stages used the same config.py; all",
                  "outputs are unchanged on disk; every file in outputs/ was produced by a stage.", ""]
    lines += ["## Upstream sources", "", "| File | Source URL / fingerprint | sha256 | bytes | rows |", "|---|---|---|---|---|"]
    s01 = recs.get("s01_extract", {})
    for i in s01.get("inputs", []):
        lines.append(f"| {i['path']} | source database; mtime {i.get('mtime')}; sha256 of first {i.get('sha256_first_bytes')} bytes | "
                     f"{i.get('sha256_partial')} | {i['bytes']} | |")
    for o in recs.get("s02_fetch", {}).get("outputs", []):
        extra = o.get("url", "")
        if o.get("release"):
            extra += f" (release {o['release'].get('id')})"
        lines.append(f"| {o['path']} | {extra} | {o['sha256']} | {o['bytes']} | {o.get('rows') or ''} |")
    lines += [""]
    for name in ORDER:
        r = recs.get(name)
        if not r:
            continue
        lines += [f"## {name}", "",
                  f"Script `{r['script']}` (sha256 {r['script_sha256'][:16]}), config.py {r['config_sha256'][:16]}, "
                  f"python {r['python']}, started {r['started_utc']}, {r['seconds']} s.", ""]
        if r["params"]:
            lines += ["Parameters: " + ", ".join(f"`{k}={v}`" for k, v in r["params"].items()), ""]
        lines += ["Inputs:", ""]
        for i in r["inputs"]:
            h = i.get("sha256") or i.get("sha256_partial")
            src = produced.get(i["path"], ("source", "", None))[0]
            lines.append(f"- `{i['path']}` from {src}, sha256 {h[:16]}, {i['bytes']} bytes")
        lines += ["", "Outputs:", ""]
        for o in r["outputs"]:
            rows = f", {o['rows']} rows" if o.get("rows") is not None else ""
            lines.append(f"- `{o['path']}` sha256 {o['sha256'][:16]}, {o['bytes']} bytes{rows}")
        lines += ["", "Log:", "", "```"]
        lines += [n for n in r["notes"] if not n.startswith(("start ", "end ", "input ", "output ", "param "))]
        lines += ["```", ""]
    with Stage("s09_provenance", __file__) as st:
        for name in ORDER:
            p = os.path.join(PROV_DIR, name + ".json")
            if os.path.exists(p):
                st.input(p, role="stage record")
        for pr in problems:
            st.note("PROBLEM: " + pr)
        st.note(f"verification {'FAILED' if problems else 'passed'}: {len(produced)} produced files checked")
        out = os.path.join(ROOT, "PROVENANCE.md")
        with open(out, "w") as f:
            f.write("\n".join(lines))
        st.output(out, role="human-readable provenance report")
    if problems:
        sys.exit(1)


if __name__ == "__main__":
    main()
